spring:
  application:
    name: movie-service
  datasource:
    url: ${MOVIE_DB_URL:jdbc:postgresql://localhost:5432/movie}
    username: ${MOVIE_DB_USERNAME:movie}
    password: ${MOVIE_DB_PASSWORD:movie}

server:
  port: 8080